### ISSUE TITLE
not connecting on OpenSSH_6.9p1, OpenSSL 1.0.2c 12 Jun 2015

### ISSUE THREAD

**Issue by BeTeK** [FauxFaux/PuTTYTray#201]
I have two machines running "OpenSSH_6.9p1, OpenSSL 1.0.2c 12 Jun 2015" from arch linux and cannot connect to those servers. Vanilla putty can connect with no problem.

Also I installed clean windows on virtual machine and had same results.

Tried with putty tray 0.63-t022 BETA

**Comment by vrabac** [comment]
I have had same issue yesterday when i updated my Server running with the Archlinux

The version 0.64 works fine.

Quoting [PuTTYTray] 0.64-based release (#185):
https://github.com/FauxFaux/PuTTYTray/issues/185#issuecomment-92013895

I have uploaded a provisional build against 0.64: https://puttytray.goeswhere.com/download/v023/putty.exe

I've written a wiki page with the state of features and testing of said features:
https://github.com/FauxFaux/PuTTYTray/wiki/Features-and-testing

I'll try and find time to test some more things before publicising this release. Any help would be greatly appreciated. Please edit the wiki page or comment if you successfully test a feature, or raise bugs if you find any.

**Comment by simon--taylor** [comment]
The problem is caused by the "Diffie-Hellman group exchange" key exchange option. OpenSSH is removing support for old versions of the message format  and PuTTY 0.65 will support the new format ([PuTTY wish rfc4419](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/rfc4419.html)). OpenSSH is backwards compatible with older versions of PuTTY but this doesn't work with PuTTYTray because the 'p' at the start of the version number in "PuTTY_Release_p0.63_t022" breaks the OpenSSH version detection.

The provisional build against 0.64 defaults to "ECDG key exchange" which works around the problem.

**Comment by BeTeK** [comment]
That version seems to work. Thanks :)

**Comment by afritsch** [comment]
Same problem here on an Arch VPS.
Workaround for now with the current version (p0.63-t022): move one of the other kex algorithms to the top (it's a bit weaker encryption but no worries for security).
![image](https://cloud.githubusercontent.com/assets/497652/8662840/30107f02-29c4-11e5-9558-499bdd54d881.png)

**Comment by FauxFaux** [comment]
0.65-p025 can connect to a 1:6.9p1-2 (Debian testing) server with the default configuration.

If you have any other examples of servers that can't be connected to, please re-open the issue.
