### ISSUE TITLE
[RFE] Support for curve25519-sha256@libssh.org

### ISSUE THREAD

**Issue by mrc0mmand** [FauxFaux/PuTTYTray#204]
Current version of PuTTYTray (unlike [PuTTY](http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=commit;h=541abf92583cd93f3952aa0e3b8f61ba9251f3fa)) supports only NIST ECDH key exchange protocols, which are considered insecure. Due to recent OpenSSH update, which (temporarily) broke diffie-hellman-group-exchange in PuTTYTray, there are currently 'no' safe key exchange protocols available. It would be great to have [curve25519-sha256@libssh.org](https://git.libssh.org/projects/libssh.git/tree/doc/curve25519-sha256@libssh.org.txt) as another option.

**Comment by FauxFaux** [comment]
PuTTYTray contained the ECDH code due to being released from PuTTY Mainline.  It appears that upstream have decided this code isn't ready for release, and have stopped including it; it was missing from their 0.64, and is still missing from 0.65.

p0.65-t025 is based off 0.65, not off mainline (although the git history is waay messed up because I'm bad at computer), so shouldn't have any of the issues, but, alas, also doesn't have any ECDH support.

I'm not keen on shipping stuff that upstream aren't ready to ship, especially when it's crypto/security/compatability related.

Perhaps taking this up with PuTTY upstream would be a better plan?

**Comment by mmozeiko** [comment]
Are you sure mainline putty doesn't have ECDH? I see code for ECDH in master branch here: http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=blob;f=sshecc.c;h=5f170215dbc2dd9764158b5334254943ae40709c;hb=HEAD#l2893

**Comment by cz-michi** [comment]
snapshot sources here: http://www.chiark.greenend.org.uk/~sgtatham/putty/snapshot.html
aren't helpful?

thanks for investigation

**Comment by cz-michi** [comment]
finally?
http://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

> Support for elliptic-curve cryptography (the NIST curves and 25519), for host keys, user authentication keys, and key exchange.

**Comment by FauxFaux** [comment]
\o/

**Comment by FauxFaux** [comment]
I'm just assuming this will all get picked up by the 0.70-based release. I have no intention of backporting crypto ever again.
