### ISSUE TITLE
Pageant's options Confirm key usage and Persist keys won't get saved.

### ISSUE THREAD

**Issue by vovcacik** [FauxFaux/PuTTYTray#229]
The `Confirm key usage` and `Persist keys` context menu options in pageant aren't saved. Changing the options and restarting pageant gives me default values.

If possible, don't save it in registry, implement something portable.

**Comment by FauxFaux** [comment]
Persist keys stays on if you enable it and add keys, i.e. it is enabled because it was enabled last time.  At least, this is what is supposed to happen, and what I expect.

1. Open pageant for the first time ever.
2. Enable "persist keys".
3. Add a key.
4. Exit pageant.
5. Relaunch pageant.
6. pageant has remembered the list of keys, and the "persist keys" setting is on.

Does this match your expectations?


Confirm Key Usage can be enabled by a command-line flag, `--confirm` (like `ssh-agent`).  Maybe pageant should automatically persist this when it's set to "Start with Windows", or you can add the flag yourself.

**Comment by FauxFaux** [comment]
There we go.

**Comment by vovcacik** [comment]
Thank you, that should fix the `Confirm key usage` option.

I didn't express myself clearly on the issue with `Persist keys`. It does save keys properly, but it seems I can't disable `Persist keys` option permanently. So if I don't want pageant to remember the keys I would need to manually remove them or manually disable `Persist keys` option every time as it stays enabled for me no matter what value it had last time I quit pageant.
